### ISSUE TITLE
Corrupted jupyter?

### ISSUE THREAD

**Issue by andres-fr** [okihnjo/DataLiteracy#6]
Hey guys,

Great work. I wanted to check some of the notebooks and found that I couldn't open a couple of them.

E.g. in https://github.com/okihnjo/DataLiteracy/blob/main/notebooks/analysis.ipynb
I get the error 

```
Invalid Notebook
The Notebook Does Not Appear to Be Valid JSON
Using nbformat v5.9.2 and nbconvert v7.16.0
```

Note that this is most likely not essential for your grading, just wanted to let you know in case you want to fix it.
Other notebooks can be opened just fine.

**Comment by okihnjo** [comment]
Hey, thanks for pointing it out. Never seen such an issue/error, really weird. Apparently this can have various [reasons](https://stackoverflow.com/questions/32103772/unreadable-notebook-notjsonerrornotebook-does-not-appear-to-be-json-u-n). Nevertheless, I used an older version and merged it again and resolved the issues manually. Now you should be able to look at every notebook, however there are now duplicates as the older notebook versions weren't as cleaned up as the ones that couldnt be opened. I will cleanup the notebooks more s.t. duplicates are avoided. For now, I close the issue.
